[versions]
assertk = "0.28.1"
cucumber = "7.23.0"
coroutines = "1.10.2"
exposed = "1.0.0"
dependencyManagement = "1.1.4"
flyway = "11.19.0"
h2Database = "2.4.240"
jactor-shared-lib = "v0.0.10"
java-uuid-generator = "5.2.0"
jvm = "25" # remember that .github actions also defines a JDK version
kotlin = "2.3.10"
kotlin-logging = "7.0.13"
ktlint = "14.0.1"
spring-boot = "3.5.11"
springdoc-openapi = "1.8.0"
springmockk = "4.0.2"
versions-plugin = "0.53.0"

[libraries]

# kotlin
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }

# internal dependencies
jactor-shared = { module = "com.github.jactor-rises:jactor-shared", version.ref = "jactor-shared-lib" }

# spring-boot
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }

# jetbrains exposed
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-spring-boot-starter = { module = "org.jetbrains.exposed:exposed-spring-boot-starter", version.ref = "exposed" }

# misc third party
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
h2database = { module = "com.h2database:h2", version.ref = "h2Database" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
springdoc-openapi-ui = { module = "org.springdoc:springdoc-openapi-ui", version.ref = "springdoc-openapi" }
uuid-generator = { module = "com.fasterxml.uuid:java-uuid-generator", version.ref = "java-uuid-generator" }

# test
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertk" }
cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-java8 = { module = "io.cucumber:cucumber-java8", version.ref = "cucumber" }
cucumber-junit-platform-engine = { module = "io.cucumber:cucumber-junit-platform-engine", version.ref = "cucumber" }
cucumber-spring = { module = "io.cucumber:cucumber-spring", version.ref = "cucumber" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
